services:
  - type: web
    name: gpr-game
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      pythonVersion: 3.11