services:
  - type: web
    name: gpr-game
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    pythonVersion: "3.11"